version: "3.3"
##a
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "haridtvt/ci-api"

  frontend:
    build:
      context: ./frontend
    image: "haridtvt/ci-frontend"
