apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
#  type: LoadBalancer
  externalIPs:
  - 192.168.1.1
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
  type: NodePort
