apiVersion: apps/v1
kind: Deployment
metadata:
  name: api    #name deployment
spec:
  replicas: 2    # number replica
  selector:
    matchLabels:
      app: api       # name pod
  template:
    metadata:
      labels:
        app: api   
    spec:
      containers:
        - name: api           
          image: haridtvt/ci-api:image
          ports:
            - containerPort: 3000
          # envFrom:         
          #   - configMapRef:
          #       name: db-config
          env:
            - name: DB_HOST 
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "admin"
            - name: DB_NAME 
              value: "appdb"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD

